version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/codeforlife-tmp-deploy:cached
    # Overrides default so things don't shut down after the process ends
    command: sleep infinity
    # Runs app on the same network as the database container,
    # allows "forwardPorts" in devcontainer.json function
    network_mode: service:db

  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - ../scripts/database:/docker-entrypoint-initdb.d
      - ../.postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: codeforlife
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
